### ISSUE TITLE
Use ENV variables

### ISSUE THREAD

**Issue by crstnmac** [Yashi-Chawla/coffee#16]
https://github.com/Yashi-Chawla/coffee/blob/885437efd0f9e2f0384f3f25806f85040b27de11/src/DropBoxUtilities.java#L22

adding API keys like this is a security issue. Instead use ENV variables

**Comment by yashichawla** [comment]
Since the DropBox API key lasts only for 4 hours (after which it needs to be renewed again), it was added as a variable
